### ISSUE TITLE
render todo module

### ISSUE THREAD

**Issue by confusedwdeveloper** [confusedwdeveloper/journal-app#18]
- [x] import relevant functions
- [x] Each todo will render a card with 3 items: checkbox to toggle completed status, text and remove button
- [x] function to generate each todo card and return it
- [x] Make the main root card element label so that clicking on todo text toggles the checkbox
- [x] checkbox and text inside one div
- [x] wire up checkbox and remove button of each todo
- [x] A function to render how many todos are left
- [x] render function will first filter list based on input
- [x] if no todos to show, write something like nothing to show
- [x] call todo creation func for each todo
- [x] also need to filter based on checkbox to hide completed todos
- [x] inside root div first generate text of how many todos left
- [x] then render todos based using forEach
