### ISSUE TITLE
Todo module

### ISSUE THREAD

**Issue by confusedwdeveloper** [confusedwdeveloper/journal-app#7]
This module will contain all the functions to manage the todos, mainly
 CRUD operations
- [x] set up empty todos array of object
- [x] load todos from local storage
- [x] savetodos which will call savejournal function
- [x] createtodo
- [x] remove todo function
- [x] expose todos to other files
- [x] toggle todo
- [x] set up export
- [x] Each todo will be an object with id, Status and text
- [x] test the functions
